---
    - hosts: all
      gather_facts: no
      user: ubuntu
      connection: "ssh"
      become: true

    - name: Install and configure Docker
      hosts: all
      become: true
      tasks:
        - name: Update apt package lists
          apt:
            update_cache: true

        - name: Install dependencies
          apt:
            name: "{{ packages }}"
            state: present
          vars:
            packages:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common

        - name: Add Docker's official GPG key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker's apt repository
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            state: present

        - name: Install Docker CE
          apt:
            name: docker-ce
            state: present

        - name: Install Python3.9
          apt:
            name: python3.9
            state: present

        - name: Install containerd.io and the Docker Compose plugin
          apt:
            name: "{{ packages }}"
            state: present
          vars:
            packages:
              - containerd.io
              - docker-compose-plugin
              - docker-compose

        - name: Add user to the docker group
          user:
            name: ubuntu
            group: docker
            state: present

        - name: Creates directory
          file:
            path: /home/ubuntu/Greenroad/app
            state: directory

        - name: Creates provisioning directory
          file:
            path: /home/ubuntu/Greenroad/provisioning
            state: directory

        - name: Copy app files
          copy:
            src: "{{ item }}"
            dest: /home/ubuntu/Greenroad/app
            mode: 0644
          with_items:
            - app/app
            - app/hello_world
            - app/db.sqlite3
            - app/manage.py
        
        - name: Copy docker-related files
          copy:
            src: "{{ item }}"
            dest: /home/ubuntu/Greenroad/
            mode: 0644
          with_items:
            - Dockerfile
            - docker-compose.yml
            - requirements.txt
            - entrypoint.sh

        - name: Copy monitoring-related files
          copy:
            src: "{{ item }}"
            dest: /home/ubuntu/Greenroad/provisioning
            mode: 0644
          with_items:
            - prometheus.yml
            - provisioning/dashboards/dashboard.json
            - provisioning/dashboards/dashboards.yaml
            - provisioning/datasources/datasources.yaml

        - name: create install python3-pip
          command: apt install -y python3-pip
        
        - name: create virtualenv
          become: true
          command: apt install -y python3-virtualenv

        - name: create django
          command: pip install django

        - name: create grafana-storage volumes
          command: docker volume create --name=grafana-storage
        
        - name: create grafana-log
          command: docker volume create --name=grafana-log
        
        - name: create prometheus_data volumes
          command: docker volume create --name=prometheus_data
      
        - name: Go to the folder and execute command
          command: docker-compose -f Greenroad/docker-compose.yml up -d